- hosts: 192.168.1.105
  tasks:
    - name: install using repository
      command: yum install -y yum-utils	
    - name: Add Docker repo1
      command: yum-config-manager \
               --add-repo \
               https://download.docker.com/linux/centos/docker-ce.repo	
    - name: install yum install docker-ce docker-ce-cli containerd.io 
      command: yum install docker-ce docker-ce-cli containerd.io -y
    - name: download repository 
      command: yum install docker-ce-docker-ce.x86_64 docker-ce-cli-docker-ce.x86_64 containerd.io	  	
    - name: start docker service
      command: systemctl start docker

